# Generated by Django 3.2.8 on 2021-10-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='username',
        ),
    ]
